# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "modern-11"
client_id = "fc0ee514ddf0ad572dd29660f03b84a5"
application_url = "https://incident-rocket-tr-it.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://incident-rocket-tr-it.trycloudflare.com/auth/callback",
  "https://incident-rocket-tr-it.trycloudflare.com/auth/shopify/callback",
  "https://incident-rocket-tr-it.trycloudflare.com/api/auth/callback",
  "https://incident-rocket-tr-it.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "myshop199807.myshopify.com"
